# SPDX-FileCopyrightText: 2024 deltanedas <39013340+deltanedas@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 deltanedas <@deltanedas:kde.org>
# SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: antag
  id: Dragon
  name: roles-antag-dragon-name
  antagonist: true
  objective: roles-antag-dragon-objective
  requirements: # ShibaStation - Antag Playtime Requirements
  - !type:OverallPlaytimeRequirement
    time: 72000 # 20 hours
  - !type:DepartmentTimeRequirement
    department: Security
    time: 36000 # 10 hours
