# SPDX-FileCopyrightText: 2023 Nemanja <98561806+EmoGarbage404@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
#
# SPDX-License-Identifier: MIT

- type: antag
  id: SubvertedSilicon
  name: roles-antag-subverted-silicon-name
  antagonist: true
  setPreference: false
  objective: roles-antag-subverted-silicon-objective
  requirements: # ShibaStation - Antag Playtime Requirements
  - !type:OverallPlaytimeRequirement
    time: 72000 # 20 hours
  - !type:DepartmentTimeRequirement
    department: Security
    time: 36000 # 10 hours

