# SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Piras314 <p1r4s@proton.me>
# SPDX-FileCopyrightText: 2025 Theodore Lukin <66275205+pheenty@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 gluesniffler <159397573+gluesniffler@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: antag
  id: LoneAbductorAntag
  name: abductor-lone-ghost-role-name
  antagonist: true
  objective: roles-antag-abductor-objective

- type: antag
  id: AbductorAgentAntag
  name: abductor-agent-ghost-role-name
  antagonist: true
  objective: roles-antag-abductor-objective

- type: antag
  id: AbductorScientistAntag
  name: abductor-scientist-ghost-role-name
  antagonist: true
  objective: roles-antag-abductor-objective
  requirements: # ShibaStation - Antag Playtime Requirements
  - !type:OverallPlaytimeRequirement
    time: 72000 # 20 hours
  - !type:DepartmentTimeRequirement
    department: Security
    time: 36000 # 10 hours

- type: antag
  id: AbductorVictimAntag
  name: abductor-victim-role-name
  antagonist: true
  objective: roles-antag-abductor-victim